package com.demo.Model;

import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import org.springframework.web.bind.annotation.ModelAttribute;

import java.util.UUID;

@Data
@AllArgsConstructor
@ApiModel(description = "Pojo for Plans class")
public class Plans {

    private String planName;
    private String planDescription;
    private Price totalPrice;
    private Benefits benefits;

    @ApiModelProperty(notes = "Autogenerated unique UUID")
    private UUID id;
}
