package com.demo.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Generated;

import java.util.UUID;

@Data
@AllArgsConstructor
@ApiModel(description = "Pojo for Plans class")
public class Plans {

  private String planName;
  private String planDescription;
  private Price totalPrice;
  private Benefits benefits;

  @ApiModelProperty(notes = "Autogenerated unique UUID")
  @Generated
  private UUID id;
}
